version: "3.7"
services:
  frontend:
    image: ghcr.io/silenc3502/frontend-server:latest
    container_name: frontend-deploy-server
    ports:
      - "8080:8080"
    networks:
      - app

  nginx:
    image: "nginx:latest"
    container_name: frontend-deploy-nginx
    restart: unless-stopped
    depends_on:
      - frontend
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
    networks:
      - app

networks:
  app:
    driver: bridge