version: "3.7"
services:
  frontend:
    image: ghcr.io/silenc3502/frontend-server:latest
    container_name: docker-frontend-deploy-server
    networks:
      - app

networks:
  app:
    driver: bridge